DROP TYPE IF EXISTS "role" CASCADE;

DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS "user_key" CASCADE;

DROP TABLE IF EXISTS "email_verification_token" CASCADE;

DROP TABLE IF EXISTS "password_reset_token" CASCADE;

DROP TABLE IF EXISTS "learn" CASCADE;

DROP TABLE IF EXISTS "user_learn" CASCADE;

DROP TABLE IF EXISTS "time_slots" CASCADE;

DROP TABLE IF EXISTS "class" CASCADE;

DROP TABLE IF EXISTS "user_class" CASCADE;

DROP TABLE IF EXISTS "message" CASCADE;