name: "nem"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nem-network
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - nem-network

  mail:
    image: inbucket/inbucket:3.0.3
    ports:
      - "2500:2500" # SMTP
      - "9000:9000" # web interface
      - "1100:1100" # POP3

volumes:
  postgres:
  redis:

networks:
  nem-network:
    driver: bridge
