// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: class.sql

package db

import (
	"context"
	"time"
)

const addUserToClass = `-- name: AddUserToClass :exec

INSERT INTO
    "user_class" (user_id, class_id)
VALUES ($1, $2) ON CONFLICT (user_id, class_id)
DO NOTHING
`

type AddUserToClassParams struct {
	UserID  string
	ClassID string
}

func (q *Queries) AddUserToClass(ctx context.Context, arg AddUserToClassParams) error {
	_, err := q.db.ExecContext(ctx, addUserToClass, arg.UserID, arg.ClassID)
	return err
}

const createClass = `-- name: CreateClass :one

INSERT INTO
    "class" (
        name,
        learn_id,
        is_private,
        time_slot_id
    )
VALUES ($1, $2, $3, $4) RETURNING id, name, is_private, learn_id, created_at, time_slot_id
`

type CreateClassParams struct {
	Name       string
	LearnID    int32
	IsPrivate  bool
	TimeSlotID string
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (*Class, error) {
	row := q.db.QueryRowContext(ctx, createClass,
		arg.Name,
		arg.LearnID,
		arg.IsPrivate,
		arg.TimeSlotID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.LearnID,
		&i.CreatedAt,
		&i.TimeSlotID,
	)
	return &i, err
}

const deleteClass = `-- name: DeleteClass :exec

DELETE FROM "class" WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClass, id)
	return err
}

const findClass = `-- name: FindClass :one

SELECT
    cl.id, cl.name, cl.is_private, cl.learn_id, cl.created_at, cl.time_slot_id,
    c.language,
    c.topic,
    t.teacher_id,
    t.start_at,
    t.end_at
FROM "class" cl
    JOIN "learn" c ON cl.learn_id = c.id
    JOIN "time_slots" t ON cl.time_slot_id = t.id
WHERE cl.id = $1
ORDER BY cl.created_at ASC
`

type FindClassRow struct {
	ID         string
	Name       string
	IsPrivate  bool
	LearnID    int32
	CreatedAt  time.Time
	TimeSlotID string
	Language   string
	Topic      string
	TeacherID  string
	StartAt    time.Time
	EndAt      time.Time
}

func (q *Queries) FindClass(ctx context.Context, id string) (*FindClassRow, error) {
	row := q.db.QueryRowContext(ctx, findClass, id)
	var i FindClassRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.LearnID,
		&i.CreatedAt,
		&i.TimeSlotID,
		&i.Language,
		&i.Topic,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
	)
	return &i, err
}

const findClassByTeacherAndTime = `-- name: FindClassByTeacherAndTime :one

SELECT
    cl.id, cl.name, cl.is_private, cl.learn_id, cl.created_at, cl.time_slot_id,
    c.language,
    c.topic,
    t.teacher_id,
    t.start_at,
    t.end_at
FROM "class" cl
    JOIN "learn" c ON cl.learn_id = c.id
    JOIN "time_slots" t ON cl.time_slot_id = t.id
WHERE
    t.teacher_id = $1
    AND t.start_at = $2
    AND t.end_at = $3
`

type FindClassByTeacherAndTimeParams struct {
	TeacherID string
	StartAt   time.Time
	EndAt     time.Time
}

type FindClassByTeacherAndTimeRow struct {
	ID         string
	Name       string
	IsPrivate  bool
	LearnID    int32
	CreatedAt  time.Time
	TimeSlotID string
	Language   string
	Topic      string
	TeacherID  string
	StartAt    time.Time
	EndAt      time.Time
}

func (q *Queries) FindClassByTeacherAndTime(ctx context.Context, arg FindClassByTeacherAndTimeParams) (*FindClassByTeacherAndTimeRow, error) {
	row := q.db.QueryRowContext(ctx, findClassByTeacherAndTime, arg.TeacherID, arg.StartAt, arg.EndAt)
	var i FindClassByTeacherAndTimeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.LearnID,
		&i.CreatedAt,
		&i.TimeSlotID,
		&i.Language,
		&i.Topic,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
	)
	return &i, err
}

const findClassByTeacherAndTimeSlotId = `-- name: FindClassByTeacherAndTimeSlotId :one

SELECT
    cl.id, cl.name, cl.is_private, cl.learn_id, cl.created_at, cl.time_slot_id,
    c.language,
    c.topic,
    t.teacher_id,
    t.start_at,
    t.end_at
FROM "class" cl
    JOIN "learn" c ON cl.learn_id = c.id
    JOIN "time_slots" t ON cl.time_slot_id = t.id
WHERE
    t.teacher_id = $1
    AND t.id = $2
`

type FindClassByTeacherAndTimeSlotIdParams struct {
	TeacherID string
	ID        string
}

type FindClassByTeacherAndTimeSlotIdRow struct {
	ID         string
	Name       string
	IsPrivate  bool
	LearnID    int32
	CreatedAt  time.Time
	TimeSlotID string
	Language   string
	Topic      string
	TeacherID  string
	StartAt    time.Time
	EndAt      time.Time
}

func (q *Queries) FindClassByTeacherAndTimeSlotId(ctx context.Context, arg FindClassByTeacherAndTimeSlotIdParams) (*FindClassByTeacherAndTimeSlotIdRow, error) {
	row := q.db.QueryRowContext(ctx, findClassByTeacherAndTimeSlotId, arg.TeacherID, arg.ID)
	var i FindClassByTeacherAndTimeSlotIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.LearnID,
		&i.CreatedAt,
		&i.TimeSlotID,
		&i.Language,
		&i.Topic,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
	)
	return &i, err
}

const listClasses = `-- name: ListClasses :many

SELECT
    cl.id, cl.name, cl.is_private, cl.learn_id, cl.created_at, cl.time_slot_id,
    c.language,
    c.topic,
    t.teacher_id,
    t.start_at,
    t.end_at
FROM "class" cl
    JOIN "learn" c ON cl.learn_id = c.id
    JOIN "time_slots" t ON cl.time_slot_id = t.id
ORDER BY cl.created_at ASC
`

type ListClassesRow struct {
	ID         string
	Name       string
	IsPrivate  bool
	LearnID    int32
	CreatedAt  time.Time
	TimeSlotID string
	Language   string
	Topic      string
	TeacherID  string
	StartAt    time.Time
	EndAt      time.Time
}

func (q *Queries) ListClasses(ctx context.Context) ([]*ListClassesRow, error) {
	rows, err := q.db.QueryContext(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListClassesRow
	for rows.Next() {
		var i ListClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.LearnID,
			&i.CreatedAt,
			&i.TimeSlotID,
			&i.Language,
			&i.Topic,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesOfTeacher = `-- name: ListClassesOfTeacher :many

SELECT
    cl.id, cl.name, cl.is_private, cl.learn_id, cl.created_at, cl.time_slot_id,
    c.language,
    c.topic,
    t.teacher_id,
    t.start_at,
    t.end_at
FROM "class" cl
    JOIN "learn" c ON cl.learn_id = c.id
    JOIN "time_slots" t ON cl.time_slot_id = t.id
WHERE t.teacher_id = $1
ORDER BY t.start_at ASC
`

type ListClassesOfTeacherRow struct {
	ID         string
	Name       string
	IsPrivate  bool
	LearnID    int32
	CreatedAt  time.Time
	TimeSlotID string
	Language   string
	Topic      string
	TeacherID  string
	StartAt    time.Time
	EndAt      time.Time
}

func (q *Queries) ListClassesOfTeacher(ctx context.Context, teacherID string) ([]*ListClassesOfTeacherRow, error) {
	rows, err := q.db.QueryContext(ctx, listClassesOfTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListClassesOfTeacherRow
	for rows.Next() {
		var i ListClassesOfTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.LearnID,
			&i.CreatedAt,
			&i.TimeSlotID,
			&i.Language,
			&i.Topic,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesOfUser = `-- name: ListClassesOfUser :many

SELECT
    cl.id, cl.name, cl.is_private, cl.learn_id, cl.created_at, cl.time_slot_id,
    c.language,
    c.topic,
    t.teacher_id,
    t.start_at,
    t.end_at
FROM "class" cl
    JOIN "user_class" uc ON cl.id = uc.class_id
    JOIN "learn" c ON cl.learn_id = c.id
    JOIN "time_slots" t ON cl.time_slot_id = t.id
WHERE uc.user_id = $1
ORDER BY uc.created_at ASC
`

type ListClassesOfUserRow struct {
	ID         string
	Name       string
	IsPrivate  bool
	LearnID    int32
	CreatedAt  time.Time
	TimeSlotID string
	Language   string
	Topic      string
	TeacherID  string
	StartAt    time.Time
	EndAt      time.Time
}

func (q *Queries) ListClassesOfUser(ctx context.Context, userID string) ([]*ListClassesOfUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listClassesOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListClassesOfUserRow
	for rows.Next() {
		var i ListClassesOfUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.LearnID,
			&i.CreatedAt,
			&i.TimeSlotID,
			&i.Language,
			&i.Topic,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInClass = `-- name: ListUsersInClass :many

SELECT u.id, u.email, u.email_verified, u.first_name, u.last_name, u.role, u.prefered_language, u.avatar_file_path, u.avatar_url, u.created_at, u.updated_at
FROM "user" u
    JOIN "user_class" uc ON u.id = uc.user_id
WHERE uc.class_id = $1
`

func (q *Queries) ListUsersInClass(ctx context.Context, classID string) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersInClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.PreferedLanguage,
			&i.AvatarFilePath,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromClass = `-- name: RemoveUserFromClass :exec

DELETE FROM "user_class" WHERE user_id = $1 AND class_id = $2
`

type RemoveUserFromClassParams struct {
	UserID  string
	ClassID string
}

func (q *Queries) RemoveUserFromClass(ctx context.Context, arg RemoveUserFromClassParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromClass, arg.UserID, arg.ClassID)
	return err
}
