// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Role string

const (
	RoleStudent Role = "student"
	RoleTeacher Role = "teacher"
	RoleAdmin   Role = "admin"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

func (e Role) Valid() bool {
	switch e {
	case RoleStudent,
		RoleTeacher,
		RoleAdmin:
		return true
	}
	return false
}

func AllRoleValues() []Role {
	return []Role{
		RoleStudent,
		RoleTeacher,
		RoleAdmin,
	}
}

type Class struct {
	ID            uuid.UUID
	Name          string
	IsPrivate     bool
	TopicTaughtID int32
	TimeSlotID    uuid.UUID
	HasStarted    bool
	CreatedAt     time.Time
}

type HoursBank struct {
	Hours     int32
	StudentID uuid.UUID
	TeacherID uuid.UUID
}

type Message struct {
	ID        uuid.UUID
	Text      string
	UserID    uuid.UUID
	ClassID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type SpokenLanguage struct {
	ID          uuid.UUID
	Language    string
	Proficiency string
}

type StudentClass struct {
	StudentID uuid.UUID
	ClassID   uuid.UUID
	CreatedAt time.Time
}

type StudentsTeacher struct {
	StudentID uuid.UUID
	TeacherID uuid.UUID
}

type Subscription struct {
	ID    uuid.UUID
	Name  string
	Hours int32
}

type SubscriptionStudent struct {
	StudentID      uuid.UUID
	TeacherID      uuid.UUID
	SubscriptionID uuid.UUID
}

type Teacher struct {
	ID       uuid.UUID
	Bio      string
	HourRate int32
}

type TeacherSpokenLanguage struct {
	SpokenLanguageID uuid.UUID
	TeacherID        uuid.UUID
}

type TeacherTopicTaught struct {
	TeacherID     uuid.UUID
	TopicTaughtID int32
}

type TimeSlot struct {
	ID        uuid.UUID
	StartAt   time.Time
	EndAt     time.Time
	TeacherID uuid.UUID
}

type TopicTaught struct {
	ID       int32
	Topic    string
	Language string
}

type User struct {
	ID               uuid.UUID
	Email            string
	FirstName        string
	LastName         string
	Role             Role
	PreferedLanguage string
	AvatarFilePath   string
	AvatarUrl        string
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
}
