// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: teacher.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO "teacher" (id, bio, hour_rate)
VALUES ($1, $2, $3)
RETURNING id, bio, hour_rate, top_agent
`

type CreateTeacherParams struct {
	ID       uuid.UUID
	Bio      string
	HourRate int32
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (*Teacher, error) {
	row := q.db.QueryRowContext(ctx, createTeacher, arg.ID, arg.Bio, arg.HourRate)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.Bio,
		&i.HourRate,
		&i.TopAgent,
	)
	return &i, err
}

const findTeacherByID = `-- name: FindTeacherByID :one
SELECT "user".id, "user".email, "user".first_name, "user".last_name, "user".role, "user".prefered_language, "user".avatar_file_path, "user".avatar_url, "user".created_at, "user".updated_at,
    "teacher"."bio",
    "teacher"."hour_rate",
    "teacher"."top_agent",
    "teacher_ratings"."rating",
    ARRAY(
        SELECT ROW(
                "language"."language",
                "spoken_language"."proficiency"
            )
        FROM "teacher_spoken_language"
            JOIN "spoken_language" ON "spoken_language"."id" = "teacher_spoken_language"."spoken_language_id"
            JOIN "language" ON "language"."id" = "spoken_language"."language_id"
        WHERE "teacher_spoken_language"."teacher_id" = "teacher"."id"
    ) AS "spoken_languages",
    ARRAY(
        SELECT "topics"."topic"
        FROM teacher_topic
            JOIN "topics" ON "topics"."id" = teacher_topic."topic_id"
        WHERE teacher_topic."teacher_id" = "teacher"."id"
    ) AS "topics_taught"
FROM "user"
    JOIN "teacher" ON "teacher"."id" = "user"."id"
    LEFT JOIN "teacher_ratings" ON "teacher_ratings"."teacher_id" = "teacher"."id"
WHERE teacher.id = $1
`

type FindTeacherByIDRow struct {
	ID               uuid.UUID
	Email            string
	FirstName        string
	LastName         string
	Role             Role
	PreferedLanguage string
	AvatarFilePath   string
	AvatarUrl        string
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
	Bio              string
	HourRate         int32
	TopAgent         bool
	Rating           sql.NullString
	SpokenLanguages  interface{}
	TopicsTaught     interface{}
}

func (q *Queries) FindTeacherByID(ctx context.Context, id uuid.UUID) (*FindTeacherByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findTeacherByID, id)
	var i FindTeacherByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.PreferedLanguage,
		&i.AvatarFilePath,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.HourRate,
		&i.TopAgent,
		&i.Rating,
		&i.SpokenLanguages,
		&i.TopicsTaught,
	)
	return &i, err
}

const listTeachers = `-- name: ListTeachers :many
SELECT "user".id, "user".email, "user".first_name, "user".last_name, "user".role, "user".prefered_language, "user".avatar_file_path, "user".avatar_url, "user".created_at, "user".updated_at,
    "teacher"."bio",
    "teacher"."hour_rate",
    "teacher"."top_agent",
    "teacher_ratings"."rating",
    ARRAY(
        SELECT ROW(
                "language"."language",
                "spoken_language"."proficiency"
            )
        FROM "teacher_spoken_language"
            JOIN "spoken_language" ON "spoken_language"."id" = "teacher_spoken_language"."spoken_language_id"
            JOIN "language" ON "language"."id" = "spoken_language"."language_id"
        WHERE "teacher_spoken_language"."teacher_id" = "teacher"."id"
    ) AS "spoken_languages",
    ARRAY(
        SELECT "topics"."topic"
        FROM teacher_topic
            JOIN "topics" ON "topics"."id" = teacher_topic."topic_id"
        WHERE teacher_topic."teacher_id" = "teacher"."id"
    ) AS "topics_taught"
FROM "user"
    JOIN "teacher" ON "teacher"."id" = "user"."id"
    LEFT JOIN "teacher_ratings" ON "teacher_ratings"."teacher_id" = "teacher"."id"
LIMIT 7
`

type ListTeachersRow struct {
	ID               uuid.UUID
	Email            string
	FirstName        string
	LastName         string
	Role             Role
	PreferedLanguage string
	AvatarFilePath   string
	AvatarUrl        string
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
	Bio              string
	HourRate         int32
	TopAgent         bool
	Rating           sql.NullString
	SpokenLanguages  interface{}
	TopicsTaught     interface{}
}

func (q *Queries) ListTeachers(ctx context.Context) ([]*ListTeachersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTeachersRow
	for rows.Next() {
		var i ListTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.PreferedLanguage,
			&i.AvatarFilePath,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.HourRate,
			&i.TopAgent,
			&i.Rating,
			&i.SpokenLanguages,
			&i.TopicsTaught,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersOfStudent = `-- name: ListTeachersOfStudent :many
SELECT "user".id, "user".email, "user".first_name, "user".last_name, "user".role, "user".prefered_language, "user".avatar_file_path, "user".avatar_url, "user".created_at, "user".updated_at,
    "teacher"."bio",
    "teacher"."hour_rate",
    "teacher"."top_agent",
    "teacher_ratings"."rating",
    ARRAY(
        SELECT ROW(
                "language"."language",
                "spoken_language"."proficiency"
            )
        FROM "teacher_spoken_language"
            JOIN "spoken_language" ON "spoken_language"."id" = "teacher_spoken_language"."spoken_language_id"
            JOIN "language" ON "language"."id" = "spoken_language"."language_id"
        WHERE "teacher_spoken_language"."teacher_id" = "teacher"."id"
    ) AS "spoken_languages",
    ARRAY(
        SELECT "topics"."topic"
        FROM teacher_topic
            JOIN "topics" ON "topics"."id" = teacher_topic."topic_id"
        WHERE teacher_topic."teacher_id" = "teacher"."id"
    ) AS "topics_taught"
FROM "user"
    JOIN "teacher" ON "teacher"."id" = "user"."id"
    JOIN "students_of_teacher" ON "students_of_teacher"."teacher_id" = "teacher"."id"
    LEFT JOIN "teacher_ratings" ON "teacher_ratings"."teacher_id" = "teacher"."id"
WHERE "students_of_teacher"."student_id" = $1
`

type ListTeachersOfStudentRow struct {
	ID               uuid.UUID
	Email            string
	FirstName        string
	LastName         string
	Role             Role
	PreferedLanguage string
	AvatarFilePath   string
	AvatarUrl        string
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
	Bio              string
	HourRate         int32
	TopAgent         bool
	Rating           sql.NullString
	SpokenLanguages  interface{}
	TopicsTaught     interface{}
}

func (q *Queries) ListTeachersOfStudent(ctx context.Context, studentID uuid.UUID) ([]*ListTeachersOfStudentRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeachersOfStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTeachersOfStudentRow
	for rows.Next() {
		var i ListTeachersOfStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.PreferedLanguage,
			&i.AvatarFilePath,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.HourRate,
			&i.TopAgent,
			&i.Rating,
			&i.SpokenLanguages,
			&i.TopicsTaught,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
