// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: timeslots.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addTimeSlot = `-- name: AddTimeSlot :one
INSERT INTO "time_slots" (
        "teacher_id",
        "start_at",
        "end_at"
    )
VALUES ($1, $2, $3)
RETURNING id, start_at, end_at, teacher_id
`

type AddTimeSlotParams struct {
	TeacherID uuid.UUID
	StartAt   time.Time
	EndAt     time.Time
}

func (q *Queries) AddTimeSlot(ctx context.Context, arg AddTimeSlotParams) (*TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, addTimeSlot, arg.TeacherID, arg.StartAt, arg.EndAt)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.StartAt,
		&i.EndAt,
		&i.TeacherID,
	)
	return &i, err
}

const deleteTimeSlot = `-- name: DeleteTimeSlot :exec
DELETE FROM "time_slots"
WHERE "id" = $1
    AND "teacher_id" = $2
`

type DeleteTimeSlotParams struct {
	ID        uuid.UUID
	TeacherID uuid.UUID
}

func (q *Queries) DeleteTimeSlot(ctx context.Context, arg DeleteTimeSlotParams) error {
	_, err := q.db.ExecContext(ctx, deleteTimeSlot, arg.ID, arg.TeacherID)
	return err
}

const findTimeSlot = `-- name: FindTimeSlot :one
SELECT id, start_at, end_at, teacher_id
FROM "time_slots"
WHERE "id" = $1
`

func (q *Queries) FindTimeSlot(ctx context.Context, id uuid.UUID) (*TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, findTimeSlot, id)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.StartAt,
		&i.EndAt,
		&i.TeacherID,
	)
	return &i, err
}

const findTimeSlotsTimeRange = `-- name: FindTimeSlotsTimeRange :many
SELECT id, start_at, end_at, teacher_id
FROM "time_slots"
WHERE "teacher_id" = $1
    AND "start_at" >= $2
    AND "end_at" <= $3
`

type FindTimeSlotsTimeRangeParams struct {
	TeacherID uuid.UUID
	StartAt   time.Time
	EndAt     time.Time
}

func (q *Queries) FindTimeSlotsTimeRange(ctx context.Context, arg FindTimeSlotsTimeRangeParams) ([]*TimeSlot, error) {
	rows, err := q.db.QueryContext(ctx, findTimeSlotsTimeRange, arg.TeacherID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.TeacherID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersAvailableTimeSlots = `-- name: ListTeachersAvailableTimeSlots :many
SELECT ts.id, ts.start_at, ts.end_at, ts.teacher_id,
    c."id" AS class_id,
    c.is_private,
    COUNT(sc."student_id") AS num_users
FROM "time_slots" ts
    LEFT JOIN "class" c ON ts."id" = c."time_slot_id"
    LEFT JOIN "student_class" sc ON c."id" = sc."class_id"
WHERE ts."teacher_id" = $1
    AND (
        c.is_private = false
        OR c.is_private is NULL
    )
    AND ts.id NOT IN (
        SELECT c.time_slot_id
        FROM class c
            JOIN student_class sc ON c.id = sc.class_id
        WHERE sc.student_id = '54fa2b35-fd53-4aaa-8264-26bd738c90cc'
    )
GROUP BY ts."id",
    c."id"
HAVING COUNT(sc.student_id) < 4
`

type ListTeachersAvailableTimeSlotsRow struct {
	ID        uuid.UUID
	StartAt   time.Time
	EndAt     time.Time
	TeacherID uuid.UUID
	ClassID   uuid.NullUUID
	IsPrivate sql.NullBool
	NumUsers  int64
}

func (q *Queries) ListTeachersAvailableTimeSlots(ctx context.Context, teacherID uuid.UUID) ([]*ListTeachersAvailableTimeSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeachersAvailableTimeSlots, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTeachersAvailableTimeSlotsRow
	for rows.Next() {
		var i ListTeachersAvailableTimeSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.TeacherID,
			&i.ClassID,
			&i.IsPrivate,
			&i.NumUsers,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeSlots = `-- name: ListTimeSlots :many
SELECT id, start_at, end_at, teacher_id
FROM "time_slots"
WHERE "teacher_id" = $1
`

func (q *Queries) ListTimeSlots(ctx context.Context, teacherID uuid.UUID) ([]*TimeSlot, error) {
	rows, err := q.db.QueryContext(ctx, listTimeSlots, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.TeacherID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeSlot = `-- name: UpdateTimeSlot :one
UPDATE "time_slots"
SET "start_at" = $1,
    "end_at" = $2
WHERE "id" = $3
    AND "teacher_id" = $4
RETURNING id, start_at, end_at, teacher_id
`

type UpdateTimeSlotParams struct {
	StartAt   time.Time
	EndAt     time.Time
	ID        uuid.UUID
	TeacherID uuid.UUID
}

func (q *Queries) UpdateTimeSlot(ctx context.Context, arg UpdateTimeSlotParams) (*TimeSlot, error) {
	row := q.db.QueryRowContext(ctx, updateTimeSlot,
		arg.StartAt,
		arg.EndAt,
		arg.ID,
		arg.TeacherID,
	)
	var i TimeSlot
	err := row.Scan(
		&i.ID,
		&i.StartAt,
		&i.EndAt,
		&i.TeacherID,
	)
	return &i, err
}
